# Site wide configuration

title:            Ethan Slattery
locale:           en_US
##url:              //TheSlat.github.io
mapid: mapbox.pencil
mapbox-token: "pk.eyJ1IjoidGhlc2xhdCIsImEiOiI1YmdVT0RZIn0.hmnkavENDfMfCTdZUsfq3A"


# Jekyll configuration

permalink:   /:categories/:title.html
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Ethan Slattery
  avatar: CRAU.jpg
  bio: "Describe your self."
  email: ethan.slattery@yahoo.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: TheSlat
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: ethanslattery
  xing: #username
  instagram: planomanic
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
